version: 2
jobs:
    client:
        docker:
            - image: circleci/node:latest-browsers
        steps:
            - checkout
            - run:
                name: Install NPM packages
                command: npm install
                working_directory: client
            - run:
                name: Lint
                command: npm run lint
                working_directory: client
            - run:
                name: Tests
                command: npm run test.prod
                working_directory: client
            - run:
                name: E2E
                command: npm run e2e
                working_directory: client
            - run:
                name: Build
                command: npm run build
                working_directory: client
workflows:
  version: 2
  build-deploy:
    jobs:
      - client:
