version: 2
jobs:
    client:
        docker:
            - image: circleci/node:latest-browsers
        steps:
            - checkout
            - run:
                name: Install NPM packages
                command: npm install
            - run:
                name: Lint
                command: npm run lint
            - run:
                name: Tests
                command: npm run test.prod
            - run:
                name: E2E
                command: npm run e2e
            - run:
                name: Build
                command: npm run build.github
            - run:
                name: Deply
                commang: npm run deploy.github
workflows:
  version: 2
  build-deploy:
    jobs:
      - client
