version: 2
jobs:
    client:
        docker:
            - image: circleci/node:latest-browsers
        steps:
            - checkout
            - run:
                name: Install NPM packages
                command: npm install
            - run:
                name: Build
                command: npm run build.github
            - run:
                name: Deploy
                command: ../node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN
                working_directory: dist

workflows:
  version: 2
  build-deploy:
    jobs:
      - client
